name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Baixar o código do repositório
      uses: actions/checkout@v4
      
    - name: 2. Instalar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: 3. Instalar as dependências (NPM)
      run: npm ci
      
    - name: 4. Instalar o motor dos navegadores
      run: npx playwright install --with-deps
      
    - name: 5. Rodar o nosso teste de Login
      run: npx playwright test

    - name: 6. Salvar o Relatório (Artefato)
      uses: actions/upload-artifact@v4
      if: always() # A palavra mágica: Salva a evidência MESMO SE o passo 5 falhar!
      with:
        name: relatorio-testes
        path: playwright-report/
        retention-days: 10 # Guarda o zip por 10 dias no GitHub